version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
  pre_build:
    commands:
      - echo Logging in to Angular application poc...
      - npm install --force
  build:
    commands:
      - echo Build started on `date`
      - npm run build
      #- npm run start 
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the files into s3 bucket
      - aws s3 sync dist/ s3://amcart-web-ui --delete
      - aws cloudfront create-invalidation --distribution-id E2WXE0XKER0T4G --paths "/*"
      - while [ $(aws cloudfront get-distribution --id E2WXE0XKER0T4G | grep -c Deployed) -eq 0 ]; do echo "sleep 60s"; sleep 60;